language: c

notifications:
  email: false


sudo: required
dist: trusty

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

matrix:
  include:
    - os: linux
      compiler: clang
      env: ANALYZE=true
    - os: osx
      compiler: clang
      env: ANALYZE=true

addons:
  apt:
    sources:
      - sourceline: 'deb http://us.archive.ubuntu.com/ubuntu/ xenial main restricted universe multiverse'
      - sourceline: 'deb http://us.archive.ubuntu.com/ubuntu/ xenial-updates main restricted universe multiverse'
    packages:
      - libglfw3-dev
      - libglew-dev
      - clang
      - gcc
      - binutils
      - libc6

before_script:
  - export SCAN_BUILD=""
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; brew install -v glfw glew; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$ANALYZE" = "true" ]; then brew update; brew install -v llvm; export SCAN_BUILD=/usr/local/opt/llvm/share/clang/tools/scan-build/bin/scan-build; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$ANALYZE" = "true" ]; then export SCAN_BUILD=scan-build; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then wget -O cmake.sh https://cmake.org/files/v3.10/cmake-3.10.3-Linux-x86_64.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo sh cmake.sh --skip-license --exclude-subdir --prefix=/usr/local; fi

script:
  - mkdir -p build && cd build
  - $SCAN_BUILD /usr/local/bin/cmake -DCMAKE_C_COMPILER=$CC ..
  - $SCAN_BUILD /usr/local/bin/cmake --build .
