language: c

notifications:
  email: false


sudo: required
dist: trusty

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

env:
  - CFLAGS=-Dsingle
  - CFLAGS=

matrix:
  include:
    - os: linux
      compiler: clang
      env: ANALYZE=true
    - os: osx
      compiler: clang
      env: ANALYZE=true

before_script:
  - export SCAN_BUILD=""
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; brew install -v homebrew/versions/glfw3 glew; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$ANALYZE" = "true" ]; then sudo apt-get update -qq; sudo apt-get install -qq clang-3.5; export SCAN_BUILD=scan-build-3.5; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$ANALYZE" = "true" ]; then brew update; brew install -v llvm37; export SCAN_BUILD=scan-build-3.7; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository 'deb http://us.archive.ubuntu.com/ubuntu/ xenial main restricted universe multiverse'; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository 'deb http://us.archive.ubuntu.com/ubuntu/ xenial-updates main restricted universe multiverse'; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -y; sudo apt-get install -y pkg-config libxcursor-dev libxinerama-dev libxrandr-dev libxi-dev libglfw3 libglfw3-dev libglew-dev; fi

script:
  - $SCAN_BUILD make CC=$CC CFLAGS=$FLAGS
